// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFTIQRcFSDY_7chB_fl6l-CgmOT3H5IRM',
    appId: '1:518797551820:web:65c496d4f21f97bde57a69',
    messagingSenderId: '518797551820',
    projectId: 'tiktok-abc-mjk',
    authDomain: 'tiktok-abc-mjk.firebaseapp.com',
    storageBucket: 'tiktok-abc-mjk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0voW3ruK2d5znhLkZUZ1y5juzTVHEUQ8',
    appId: '1:518797551820:android:d8ee04bc2618088be57a69',
    messagingSenderId: '518797551820',
    projectId: 'tiktok-abc-mjk',
    storageBucket: 'tiktok-abc-mjk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB10MBa4aV7j7Fxfi58Xijo_vnwAqQ4aws',
    appId: '1:518797551820:ios:d408f4499059ed00e57a69',
    messagingSenderId: '518797551820',
    projectId: 'tiktok-abc-mjk',
    storageBucket: 'tiktok-abc-mjk.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
